### ISSUE TITLE
I am Confused 

### ISSUE THREAD

**Issue by ghost** [pman5534/lot-of-working-bookmarklet#2]
Could you please make a descripsion of all of you bookmarklets, and create a HTML folder with all of the bookmarklets without a discription i am clicking into the code and wondering what it is

**Comment by pman5534** [comment]
i will fix it i just haven't had time to fix and organize this stuff because i just found out how to make folders so yeah

**Comment by pman5534** [comment]
also one of my friends went on my computer and get rid of most of my bookmarklets so i need to go find those and get them back

**Comment by ghost** [comment]
OK thank you
